// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


#nullable disable

namespace MyFlightbook.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302134501_SuperUser")]
    partial class SuperUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFlightbook.Api.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("GlassUpgradeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ICAO")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("InstanceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int>("MakeModelId")
                        .HasColumnType("int");

                    b.Property<string>("PublicNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MakeModelId");

                    b.ToTable("aircraft");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyJurisdiction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsInstructor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreferredTimeZoneId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("UsesHHMM")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("app_users");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.CategoryClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatClass")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("category_classes");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("Approaches")
                        .HasColumnType("int");

                    b.Property<decimal>("CFI")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("CatClassOverride")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CrossCountry")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Dual")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("EngineEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EngineStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightColorHex")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("FlightEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FlightStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FullStopLandings")
                        .HasColumnType("int");

                    b.Property<decimal>("GroundSim")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("HobbsEnd")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("HobbsStart")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("HoldingProcedures")
                        .HasColumnType("bit");

                    b.Property<decimal>("IMC")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Landings")
                        .HasColumnType("int");

                    b.Property<int>("NightLandings")
                        .HasColumnType("int");

                    b.Property<decimal>("Nighttime")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("PIC")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<decimal>("SIC")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("SimulatedIFR")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalFlightTime")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AppUserId");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.FlightProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DecValue")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("IntValue")
                        .HasColumnType("int");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("flight_properties");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.MakeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArmyMDS")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("CategoryClassId")
                        .HasColumnType("int");

                    b.Property<int>("EngineType")
                        .HasColumnType("int");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("HasFlaps")
                        .HasColumnType("bit");

                    b.Property<bool>("Is200HP")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCertifiedSinglePilot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplex")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConstantProp")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHighPerf")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMotorGlider")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMultiEngineHelicopter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRetract")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTailWheel")
                        .HasColumnType("bit");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryClassId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("make_models");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("Flags")
                        .HasColumnType("bigint");

                    b.Property<string>("FormatString")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("ShortTitle")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("property_types");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.UserAircraft", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int>("AvionicsTechnology")
                        .HasColumnType("int");

                    b.Property<bool>("HideFromSelection")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("PrivateNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("RoleForPilot")
                        .HasColumnType("int");

                    b.HasKey("AppUserId", "AircraftId");

                    b.HasIndex("AircraftId");

                    b.ToTable("user_aircraft");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.Aircraft", b =>
                {
                    b.HasOne("MyFlightbook.Api.Models.MakeModel", "MakeModel")
                        .WithMany("Aircraft")
                        .HasForeignKey("MakeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MyFlightbook.Api.Models.AircraftMaintenance", "Maintenance", b1 =>
                        {
                            b1.Property<int>("AircraftId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Last100")
                                .HasPrecision(8, 2)
                                .HasColumnType("decimal(8,2)");

                            b1.Property<DateTime?>("LastAltimeter")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("LastAnnual")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("LastELT")
                                .HasColumnType("datetime2");

                            b1.Property<decimal>("LastNewEngine")
                                .HasPrecision(8, 2)
                                .HasColumnType("decimal(8,2)");

                            b1.Property<decimal>("LastOilChange")
                                .HasPrecision(8, 2)
                                .HasColumnType("decimal(8,2)");

                            b1.Property<DateTime?>("LastStatic")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("LastTransponder")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("LastVOR")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2048)
                                .HasColumnType("nvarchar(2048)");

                            b1.Property<DateTime?>("RegistrationExpiration")
                                .HasColumnType("datetime2");

                            b1.HasKey("AircraftId");

                            b1.ToTable("aircraft");

                            b1.WithOwner()
                                .HasForeignKey("AircraftId");
                        });

                    b.Navigation("Maintenance")
                        .IsRequired();

                    b.Navigation("MakeModel");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.Flight", b =>
                {
                    b.HasOne("MyFlightbook.Api.Models.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFlightbook.Api.Models.AppUser", "User")
                        .WithMany("Flights")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.FlightProperty", b =>
                {
                    b.HasOne("MyFlightbook.Api.Models.Flight", "Flight")
                        .WithMany("Properties")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFlightbook.Api.Models.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.MakeModel", b =>
                {
                    b.HasOne("MyFlightbook.Api.Models.CategoryClass", "CategoryClass")
                        .WithMany("MakeModels")
                        .HasForeignKey("CategoryClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFlightbook.Api.Models.Manufacturer", "Manufacturer")
                        .WithMany("MakeModels")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryClass");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.UserAircraft", b =>
                {
                    b.HasOne("MyFlightbook.Api.Models.Aircraft", "Aircraft")
                        .WithMany("UserAircraft")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFlightbook.Api.Models.AppUser", "User")
                        .WithMany("UserAircraft")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.Aircraft", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("UserAircraft");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.AppUser", b =>
                {
                    b.Navigation("Flights");

                    b.Navigation("UserAircraft");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.CategoryClass", b =>
                {
                    b.Navigation("MakeModels");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.Flight", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.MakeModel", b =>
                {
                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.Manufacturer", b =>
                {
                    b.Navigation("MakeModels");
                });

            modelBuilder.Entity("MyFlightbook.Api.Models.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
